name: chat app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "12345678"
          MYSQL_DATABASE: "chat_app"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "12345678"
        ports:
          - 3306:3306
        options: --health-cmd="some-mysql ping -h 127.0.0.1 -u root --password=12345678" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=12345678" >> .env
          echo "DB_NAME=chat_app" >> .env
          echo "JWT_SECRET=123456666" >> .env
          echo "JWT_EXPIRES_IN=3600s" >> .env

      - name: Run migrations
        run: npm run migration:run

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build
